# Welcome to Jekyll!
#

# Site settings
title: Sebywo Graffiti
description: |
  Wonderful text goes here
owner: sebywograffiti
first_published: 2019 # if migrating another site, the year of your first publish
email: sebywograffiti@gmail.com
baseurl: "/sebywo-graffitti" # the subpath of your site, e.g. /blog
url: "http://sebbiewo.github.io" # the base hostname & protocol for your site
social:
  twitter: 
  github: https://github.com/sebbiewo
  linkedin-square: 
  facebook-official: 
  google-plus-square: 
  #email: /contact/
  #flickr:
  instagram: sebywo-graffiti
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
